name: Release with artifact

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Run tests
        run: |
          make test
      - name: Lint programs
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
          skip-cache: true
          skip-save-cache: true
          install-mode: binary
      - name: Set version
        id: version
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Build platform binaries
        run: VERSION=${{ steps.version.outputs.version }} make all
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/tender-linux-amd64
            dist/tender-linux-arm64
            dist/tender-darwin-amd64
            dist/tender-darwin-arm64
            dist/tender-linux-amd64.tar.gz
            dist/tender-linux-arm64.tar.gz
            dist/tender-darwin-amd64.tar.gz
            dist/tender-darwin-arm64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
